version: '3'

volumes:
  postgres_data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 123456

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: 123456
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
    ports:
      - 8082:8080
    depends_on:
      - mysql

  db_postgres:
    image: postgres
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432
    ports:
      - 5432:5432
    container_name: db_postgres

#  sisvendas-backend:
#    build: .
#    ports:
#      - 8081:8081
#    volumes:
#      - ../logs-spring:/logs
#    container_name: sisvendas-backend
#
#  sisvendas-frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile-frontend
#    ports:
#      - 8080:80
#    container_name: sisvendas-frontend