version: '3'

services:

  db_postgres:
    image: postgres
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432
    ports:
    - 5432:5432
    container_name: db_postgres

  sisvendas-backend:
    build: .      
    ports:
    - 8081:8081
    volumes:
      - ../logs-spring:/logs
    container_name: sisvendas-backend

  sisvendas-frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend          
    ports:
    - 8080:80
    container_name: sisvendas-frontend
