version: '3'

volumes:
  postgres_data:
    driver: local

services:
  db:
    container_name: db_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pa55word
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/mysql:/var/lib/mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=pa55word
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
    ports:
      - 8082:8080
    command: start-dev
    depends_on:
      - db
      
  db_postgres:
     image: postgres
     restart: always
     volumes:
       - ../pgdata:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: 123456
     expose:
       - 5432
     ports:
       - 5432:5432
     container_name: db_postgres

 #  sisvendas-backend:
#    build: .
#    ports:
#      - 8081:8081
#    volumes:
#      - ../logs-spring:/logs
#    container_name: sisvendas-backend
#
#  sisvendas-frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile-frontend
#    ports:
#      - 8080:80
#    container_name: sisvendas-frontend